heat_template_version: 2015-10-15
description: Server template

parameters:

    flavor:
        type: string
        label: Flavor
        constraints:
            - custom_constraint: nova.flavor

    availability_zone: 
        type: string
        label: Availability Zone
        default: Default


    image:
        type: string
        label: Image Name
        constraints:
            - custom_constraint: glance.image

    name:
        type: string
        label: Name of the Server
    

    key_pair:
        type: string
        label: Key Pair
        constraints:
            - custom_constraint: nova.keypair

    security_groups:
        type: comma_delimited_list
        label: Security Group(s)
        default: default

    network:
        type: string
        description: networks for the instances

resources:

    Servertemplate:
        type: OS::Nova::Server
        properties:
            flavor: {get_param: flavor}
            key_name: { get_param: key_pair}
            availability_zone: { get_param: availability_zone}
            image: {get_param: image}
            name: {get_param : name}
            networks: 
                - network: { get_param: network }
            security_groups: { get_param: security_groups}