heat_template_version: 2015-10-15
description: Server template

parameters:

    flavor:
        type: string
        label: Flavor
        constraints:
            - custom_constraint: nova.flavor

    availability_zone: 
        type: string
        label: Availability Zone
        default: Default


    image:
        type: string
        label: Image Name
        constraints:
            - custom_constraint: glance.image

    name:
        type: string
        label: Name of the Server
    

    key_pair:
        type: string
        label: Key Pair
        constraints:
            - custom_constraint: nova.keypair

    security_groups: 
        type: comma_delimited_list 
        label: Security Group(s) 
        default: [default]

    private_net:
        type: string

    subnet:
        type: string
        description: subnet for the instance

resources:

    server_port:
        type: OS::Neutron::Port
        properties:
            name: backend_port
            network_id: { get_param: private_net }
            security_groups: {get_param: security_groups}
            fixed_ips:
                - subnet_id: {get_param: subnet}    

    Servertemplate:
        type: OS::Nova::Server
        properties:
            flavor: {get_param: flavor}
            key_name: { get_param: key_pair}
            availability_zone: { get_param: availability_zone}
            image: {get_param: image}
            name: {get_param : name}
            admin_user: ubuntu
            # if I define more than one network connection (to the same network at least) it will for some reason use just one port, not both 
            # networks:  [{port: { get_param: port }, port: {get_resource: backend_port} }]
            # networks:  [{port: { get_param: port }}]    # outside port
            networks:  [{port: {get_resource: server_port} }]              

outputs:
    port:
        description: port
        value: { get_resource: server_port }