heat_template_version: 2015-10-15
description: Server template

parameters:

    flavor:
        type: string
        label: Flavor
        constraints:
            - custom_constraint: nova.flavor

    availability_zone: 
        type: string
        label: Availability Zone
        default: Default


    image:
        type: string
        label: Image Name
        constraints:
            - custom_constraint: glance.image

    name:
        type: string
        label: Name of the Server
    

    key_pair:
        type: string
        label: Key Pair
        constraints:
            - custom_constraint: nova.keypair

    security_groups:
        type: comma_delimited_list
        label: Security Group(s)
        default: default

    networks:
        type: comma_delimited_list
        description: networks for the instances
        default: []

    subnets:
        type: comma_delimited_list
        description: subnets for the instance
        default: []

    ports:
        type: comma_delimited_list
        description: ports for the instance
        default: []

resources:

    Servertemplate:
        type: OS::Nova::Server
        properties:
            flavor: {get_param: flavor}
            key_name: { get_param: key_pair}
            availability_zone: { get_param: availability_zone}
            image: {get_param: image}
            name: {get_param : name}
            security_groups: { get_param: security_groups}
            networks: 
                repeat:
                  for_each:
                    <%port%>: { get_param: ports }
                  template:
                    port: <%port%>
            networks: 
                repeat:
                  for_each:
                    <%network%>: { get_param: networks }
                  template:
                    network: <%network%>
            networks: 
                repeat:
                  for_each:
                    <%subnet%>: { get_param: subnets }
                  template:
                    subnet: <%subnet%>                    

outputs:
    networks_out:
        description: vm networks
        value: { get_attr: [Servertemplate, networks]}