heat_template_version: 2015-10-15
description: test

parameters:

    networks:
        type: comma_delimited_list
        description: networks for the instances
        default: []

    ports:
        type: comma_delimited_list
        description: ports for the instance
        default: []

resources:

    # Servertemplate:
    #     type: OS::Nova::Server
    #     properties:
    #         flavor: Cloud Computing
    #         availability_zone: Cloud Computing 2017
    #         image: ubuntu-16.04
    #         networks: 
    #             repeat:
    #               for_each:
    #                 <%port%>: { get_param: ports }
    #               template:
    #                 port: <%port%>
    #         networks: 
    #             repeat:
    #               for_each:
    #                 <%network%>: { get_param: networks }
    #               template:
    #                 network: <%network%>

  private_net:
        type: OS::Neutron::Net
        properties:
          name: private-net

  private_subnet:
        type: OS::Neutron::Subnet
        properties:
          name: private_subnet
          network_id: { get_resource: private_net }
          cidr: 172.16.2.0/24
          gateway_ip: 172.16.2.1

  router1:
        type: OS::Neutron::Router
        properties:
          name: router1
          external_gateway_info:
                network: tu-internal

  router1_interface:
        type: OS::Neutron::RouterInterface
        properties:
          router_id: { get_resource: router1 }
          subnet_id: { get_resource: private_subnet }

  CC_Security:
          type: OS::Neutron::SecurityGroup
          properties:
              name: CC_Security
              description: Ping and SSH
              rules:
                - protocol: icmp
                - protocol: tcp
                  remote_ip_prefix: 0.0.0.0/0
                  port_range_min: 22
                  port_range_max: 22
                - protocol: tcp
                  port_range_min: 5000
                  port_range_max: 5000

  server1_port:
        type: OS::Neutron::Port
        properties:
          name: server1_port
          network_id: { get_resource: private_net }
          security_groups: [ get_resource: CC_Security ]
          fixed_ips:
                - subnet_id: { get_resource: private_subnet }

  server1_floating_ip:
        type: OS::Neutron::FloatingIP
        properties:
          floating_network_id: tu-internal
          port_id: { get_resource: server1_port }

  server1:
        type: OS::Nova::Server
        properties:
          name: server1
          flavor: Cloud Computing
          availability_zone: Cloud Computing 2017
          image: ubuntu-16.04
          key_name:  group06key
          admin_user: ubuntu
        #either networks declaration works:
          # networks:
          #       - port: { get_resource: server1_port }
          networks: [ {subnet: { get_resource: private_subnet }}]
