version: "3"
services:
  backend:
    image: gitlab-registry.tubit.tu-berlin.de/jensk/cc17-docker-registry/backend:latest
    ports: 
      - "8000:80"
    volumes:
      - /etc:/hypervisor_etc
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname != assignment3-stack-frontend
