version: "3"
services:
  frontend:
    image: gitlab-registry.tubit.tu-berlin.de/jensk/cc17-docker-registry/frontend:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == assignment3-stack-frontend
    environment:
      - CC_BACKEND_SERVERS
    ports: 
      - "80:80"
    volumes:
      - /etc:/hypervisor_etc
